package de.glasergl.custom.lol.setup.model.entity;

public enum Champion {
    AATROX, AHRI, AKALI, AKSHAN, ALISTAR, AMBESSA, AMUMU, ANIVIA, ANNIE, APHELIOS, ASHE, AURELION_SOL, AURORA, AZIR, BARD, BEL_VETH, BLITZCRANK, BRAND, BRAUM, BRIAR, CAITLYN, CAMILLE, CASSIOPEIA, CHO_GATH, CORKI, DARIUS, DIANA, DRAVEN, DR_MUNDO, EKKO, ELISE, EVELYNN, EZREAL, FIDDLESTICKS, FIORA,
    FIZZ, GALIO, GANGPLANK, GAREN, GNAR, GRAGAS, GRAVES, GWEN, HECARIM, HEIMERDINGER, HWEI, ILLAOI, IRELIA, IVERN, JANNA, JARVAN_IV, JAX, JAYCE, JHIN, JINX, KAI_SA, KALISTA, KARMA, KARTHUS, KASSADIN, KATARINA, KAYLE, KAYN, KENNEN, KHA_ZIX, KINDRED, KLED, KOG_MAW, K_SANTE, LE_BLANC, LEE_SIN, LEONA,
    LILLIA, LISSANDRA, LUCIAN, LULU, LUX, MALPHITE, MALZAHAR, MAOKAI, MASTER_YI, MEL, MILIO, MISS_FORTUNE, MORDEKAISER, MORGANA, NAAFIRI, NAMI, NASUS, NAUTILUS, NEEKO, NIDALEE, NILAH, NOCTURNE, NUNU, OLAF, ORIANNA, ORNN, PANTHEON, POPPY, PYKE, QIYANA, QUINN, RAKAN, RAMMUS, REK_SAI, RELL,
    RENATA_GLASC, RENEKTON, RENGAR, RIVEN, RUMBLE, RYZE, SAMIRA, SEJUANI, SENNA, SERAPHINE, SETT, SHACO, SHEN, SHYVANA, SINGED, SION, SIVIR, SKARNER, SMOLDER, SONA, SORAKA, SWAIN, SYLAS, SYNDRA, TAHM_KENCH, TALIYAH, TALON, TARIC, TEEMO, THRESH, TRISTANA, TRUNDLE, TRYNDAMERE, TWISTED_FATE, TWITCH,
    UDYR, URGOT, VARUS, VAYNE, VEIGAR, VEL_KOZ, VEX, VI, VIEGO, VIKTOR, VLADIMIR, VOLIBEAR, WARWICK, WUKONG, XAYAH, XERATH, XIN_ZHAO, YASUO, YONE, YORICK, YUNARA, YUUMI, ZAAHEN, ZAC, ZED, ZERI, ZIGGS, ZILEAN, ZOE, ZYRA;
}
