package de.glasergl.custom.lol.setup.model.entity;

public enum Item {
    CULL, DARK_SEAL, DORANS_BLADE, DORANS_RING, DORANS_SHIELD, GUSTWALKER_HATCHLING, MOSSTOMPER_SEEDLING, SCORCHCLAW_PUP, TEAR_OF_THE_GODDESS,

    CONTROL_WARD, ELIXIR_OF_IRON, ELIXIR_OF_SORCERY, ELIXIR_OF_WRATH, HEALTH_POTION, REFILLABLE_POTION,

    ORACLE_LENS, FARSIGHT_ALTERATION, STEALTH_WARD,

    BERSERKERS_GREAVES, BOOTS, BOOTS_OF_SWIFTNESS, IONIAN_BOOTS_OF_LUCIDITY, MERCURYS_TREADS, PLATED_STEELCAPS, SORCERERS_SHOES,

    AMPLIFYING_TOME, BF_SWORD, BLASTING_WAND, CLOAK_OF_AGILITY, CLOTH_ARMOR, DAGGER, FAERIE_CHARM, GLOWING_MOTE, LONG_SWORD, NEEDLESSLY_LARGE_ROD, NULL_MAGIC_MANTLE, PICKAXE, REJUVENATION_BEAD, RUBY_CRYSTAL, SAPPHIRE_CRYSTAL,

    AETHER_WISP, BAMIS_CINDER, BANDLEGLASS_MIRROR, BLIGHTING_JEWEL, BRAMBLE_VEST, CATALYST_OF_AEONS, CAULFIELDS_WARHAMMER, CHAIN_VEST, CRYSTALLINE_BRACER, EXECUTIONERS_CALLING, FATED_ASHES, FIENDISH_CODEX, FORBIDDEN_IDOL, GIANTS_BELT, GLACIAL_BUCKLER, HAUNTING_GUISE, HEARTHBOUND_AXE, HEXDRINKER,
    HEXTECH_ALTERNATOR, KINDLEGEM, LAST_WHISPER, LOST_CHAPTER, NEGATRON_CLOAK, NOONQUIVER, OBLIVION_ORB, PHAGE, QUICKSILVER_SASH, RECTRIX, RECURVE_BOW, SCOUTS_SLINGSHOT, SEEKERS_ARMGUARD, SERRATED_DIRK, SHEEN, SPECTRES_COWL, STEEL_SIGIL, THE_BRUTALIZER,
    TIAMAT, TUNNELER, VAMPIRIC_SCEPTER, VERDANT_BARRIER, WARDENS_MAIL, WINGED_MOONPLATE, ZEAL,

    ABYSSAL_MASK, ACTUALIZER, ARCHANGELS_STAFF, ARDENT_CENSER, AXIOM_ARC, BANDLEPIPES, BANSHEES_VEIL, BASTIONBREAKER, BLACK_CLEAVER, BLACKFIRE_TORCH, BLADE_OF_THE_RUINED_KING, BLOODLETTERS_CURSE, BLOODTHIRSTER, CHEMPUNK_CHAINSWORD, COSMIC_DRIVE, CRYPTBLOOM, DAWNCORE, DEAD_MANS_PLATE, DEATHS_DANCE,
    DUSK_AND_DAWN, ECHOES_OF_HELIA, ECLIPSE, EDGE_OF_NIGHT, ENDLESS_HUNGER, ESSENCE_REAVER, EXPERIMENTAL_HEXPLATE, FIENDHUNTER_BOLTS, FORCE_OF_NATURE, FROZEN_HEART, GUARDIAN_ANGEL, GUINSOOS_RAGEBLADE, HEARTSTEEL, HEXOPTICS_C44, HEXTECH_GUNBLADE, HEXTECH_ROCKETBELT, HOLLOW_RADIANCE, HORIZON_FOCUS,
    HUBRIS, HULLBREAKER, ICEBORN_GAUNTLET, IMMORTAL_SHIELDBOW, IMPERIAL_MANDATE, INFINITY_EDGE, JAK_SHO_THE_PROTEAN, KAENIC_ROOKERN, KNIGHTS_VOW, KRAKEN_SLAYER, LIANDRYS_TORMENT, LICH_BANE, LOCKET_OF_THE_IRON_SOLARI, LORD_DOMINIKS_REGARDS, LUDENS_ECHO, MALIGNANCE, MANAMUNE, MAW_OF_MALMORTIUS,
    MEJAIS_SOULSTEALER, MERCURIAL_SCIMITAR, MIKAELS_BLESSING, MOONSTONE_RENEWER, MORELLONOMICON, MORTAL_REMINDER, NASHORS_TOOTH, NAVORI_FLICKERBLADE, OPPORTUNITY, OVERLORDS_BLOODMAIL, PHANTOM_DANCER, PROFANE_HYDRA, PROTOPLASM_HARNESS, RABADONS_DEATHCAP, RANDUINS_OMEN, RAPID_FIRECANNON,
    RAVENOUS_HYDRA, REDEMPTION, RIFTMAKER, ROD_OF_AGES, RUNAANS_HURRICANE, RYLAIS_CRYSTAL_SCEPTER, SERPENTS_FANG, SERYLDAS_GRUDGE, SHADOWFLAME, SHURELYAS_BATTLESONG, SPEAR_OF_SHOJIN, SPIRIT_VISAGE, STAFF_OF_FLOWING_WATER, STATIKK_SHIV, STERAKS_GAGE, STORMRAZOR, STORMSURGE, STRIDEBREAKER,
    SUNDERED_SKY, SUNFIRE_AEGIS, TERMINUS, THE_COLLECTOR, THORNMAIL, TITANIC_HYDRA, TRAILBLAZER, TRINITY_FORCE, UMBRAL_GLAIVE, UNENDING_DESPAIR, VOID_STAFF, VOLTAIC_CYCLOSWORD, WARMOGS_ARMOR, WHISPERING_CIRCLET, WINTERS_APPROACH, WITS_END, YOUMUUS_GHOSTBLADE, YUN_TAL_WILDARROWS, ZEKES_CONVERGENCE,
    ZHONYAS_HOURGLASS;
}
