package de.glasergl.custom.lol.setup.model.entity;

import lombok.Getter;

import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static de.glasergl.custom.lol.setup.model.entity.ItemProperty.*;

public enum Item {
    CULL(450, ATTACK_DAMAGE, ON_HIT), DARK_SEAL(350, ABILITY_POWER, HEALTH), DORANS_BOW(400, ATTACK_DAMAGE, ATTACK_SPEED, LIFE_STEAL), DORANS_BLADE(450, ATTACK_DAMAGE, HEALTH, LIFE_STEAL), DORANS_HELM(450, HEALTH, ARMOR, MAGIC_RESIST), DORANS_RING(400, ABILITY_POWER, MANA, HEALTH), DORANS_SHIELD(450, HEALTH), GUSTWALKER_HATCHLING(450), MOSSTOMPER_SEEDLING(450), SCORCHCLAW_PUP(450),
    TEAR_OF_THE_GODDESS(400, MANA),

    CONTROL_WARD(75), ELIXIR_OF_IRON(500, HEALTH, MOVEMENT), ELIXIR_OF_SORCERY(500, ABILITY_POWER, MANA), ELIXIR_OF_WRATH(500, ATTACK_DAMAGE, LIFE_STEAL), HEALTH_POTION(50, HEALTH), REFILLABLE_POTION(150, HEALTH),

    ORACLE_LENS(0), FARSIGHT_ALTERATION(0), STEALTH_WARD(0),

    BERSERKERS_GREAVES(1100, ATTACK_SPEED, MOVEMENT), BOOTS(300, MOVEMENT), BOOTS_OF_SWIFTNESS(1000, MOVEMENT), GLUTTONOUS_GREAVES(1000, MOVEMENT, LIFE_STEAL), IONIAN_BOOTS_OF_LUCIDITY(900, ABILITY_HASTE, MOVEMENT), MERCURYS_TREADS(1250, MAGIC_RESIST, MOVEMENT), PLATED_STEELCAPS(1200, ARMOR, MOVEMENT),
    SORCERERS_SHOES(1100, MAGIC_PENETRATION, MOVEMENT),

    AMPLIFYING_TOME(400, ABILITY_POWER), BF_SWORD(1300, ATTACK_DAMAGE), BLASTING_WAND(850, ABILITY_POWER), CLOAK_OF_AGILITY(600, CRITICAL_CHANCE), CLOTH_ARMOR(300, ARMOR), DAGGER(250, ATTACK_SPEED), FAERIE_CHARM(200, MANA), GLOWING_MOTE(250, ABILITY_HASTE), LONG_SWORD(350, ATTACK_DAMAGE),
    NEEDLESSLY_LARGE_ROD(1200, ABILITY_POWER), NULL_MAGIC_MANTLE(400, MAGIC_RESIST), PICKAXE(875, ATTACK_DAMAGE), REJUVENATION_BEAD(300, HEALTH), RUBY_CRYSTAL(400, HEALTH), SAPPHIRE_CRYSTAL(300, MANA),

    AETHER_WISP(900, ABILITY_POWER, MOVEMENT), BAMIS_CINDER(900, HEALTH, ABILITY_HASTE), BANDLEGLASS_MIRROR(900, ABILITY_POWER, MANA, ABILITY_HASTE), BLIGHTING_JEWEL(1100, ABILITY_POWER, MAGIC_PENETRATION), BRAMBLE_VEST(800, ARMOR), CATALYST_OF_AEONS(1300, MANA, HEALTH),
    CAULFIELDS_WARHAMMER(1050, ATTACK_DAMAGE, ABILITY_HASTE), CHAIN_VEST(800, ARMOR), CRYSTALLINE_BRACER(800, HEALTH), EXECUTIONERS_CALLING(800, ATTACK_DAMAGE), FATED_ASHES(900, ABILITY_POWER), FIENDISH_CODEX(850, ABILITY_POWER, ABILITY_HASTE), FORBIDDEN_IDOL(600, MANA), GIANTS_BELT(900, HEALTH),
    GLACIAL_BUCKLER(900, MANA, ARMOR, ABILITY_HASTE), HAUNTING_GUISE(1300, ABILITY_POWER, HEALTH), HEARTHBOUND_AXE(1200, ATTACK_DAMAGE, ATTACK_SPEED), HEXDRINKER(1300, ATTACK_DAMAGE, MAGIC_RESIST), HEXTECH_ALTERNATOR(1100, ABILITY_POWER), KINDLEGEM(800, HEALTH, ABILITY_HASTE),
    LAST_WHISPER(1450, ATTACK_DAMAGE, ARMOR_PENETRATION), LOST_CHAPTER(1200, ABILITY_POWER, MANA, ABILITY_HASTE), NEGATRON_CLOAK(850, MAGIC_RESIST), NOONQUIVER(1300, ATTACK_DAMAGE, CRITICAL_CHANCE), OBLIVION_ORB(800, ABILITY_POWER), PHAGE(1100, ATTACK_DAMAGE, HEALTH, MOVEMENT),
    QUICKSILVER_SASH(1300, MAGIC_RESIST), RECTRIX(775, ATTACK_DAMAGE, MOVEMENT), RECURVE_BOW(700, ATTACK_SPEED, ON_HIT), SCOUTS_SLINGSHOT(600, ATTACK_SPEED), SEEKERS_ARMGUARD(1600, ABILITY_POWER, ARMOR), SERRATED_DIRK(1000, ATTACK_DAMAGE, ARMOR_PENETRATION), SHEEN(900, ON_HIT, ABILITY_HASTE),
    SPECTRES_COWL(1250, HEALTH, MAGIC_RESIST), STEEL_SIGIL(1100, ATTACK_DAMAGE, ARMOR), THE_BRUTALIZER(1337, ATTACK_DAMAGE, ARMOR_PENETRATION, ABILITY_HASTE), TIAMAT(1200, ATTACK_DAMAGE, ON_HIT), TUNNELER(1150, ATTACK_DAMAGE, HEALTH), VAMPIRIC_SCEPTER(900, ATTACK_DAMAGE, LIFE_STEAL),
    VERDANT_BARRIER(1600, ABILITY_POWER, MAGIC_RESIST), WARDENS_MAIL(1000, ARMOR), WINGED_MOONPLATE(800, HEALTH, MOVEMENT), ZEAL(1200, CRITICAL_CHANCE, ATTACK_SPEED, MOVEMENT),

    ABYSSAL_MASK(2650, HEALTH, MAGIC_RESIST, ABILITY_HASTE), ACTUALIZER(2800, ABILITY_POWER, MANA, ABILITY_HASTE), ARCHANGELS_STAFF(2900, ABILITY_POWER, MANA, ABILITY_HASTE), ARDENT_CENSER(2200, ATTACK_SPEED, ABILITY_POWER, MANA, MOVEMENT),
    AXIOM_ARC(2750, ATTACK_DAMAGE, ARMOR_PENETRATION, ABILITY_HASTE), BANDLEPIPES(2300, ATTACK_SPEED, HEALTH, ARMOR, MAGIC_RESIST, ABILITY_HASTE, MOVEMENT), BANSHEES_VEIL(3000, ABILITY_POWER, MAGIC_RESIST), BASTION_BREAKER(3200, ATTACK_DAMAGE, ARMOR_PENETRATION, ABILITY_HASTE),
    BLACK_CLEAVER(3000, ATTACK_DAMAGE, ON_HIT, ARMOR_PENETRATION, HEALTH, ABILITY_HASTE, MOVEMENT), BLACKFIRE_TORCH(2800, ABILITY_POWER, MANA, ABILITY_HASTE), BLADE_OF_THE_RUINED_KING(3200, ATTACK_DAMAGE, ATTACK_SPEED, ON_HIT, LIFE_STEAL),
    BLOOD_LETTERS_CURSE(2900, ABILITY_POWER, MAGIC_PENETRATION, HEALTH, ABILITY_HASTE), BLOOD_THIRSTER(3400, ATTACK_DAMAGE, LIFE_STEAL), CHEMPUNK_CHAINSWORD(3000, ATTACK_DAMAGE, HEALTH, ABILITY_HASTE), COSMIC_DRIVE(3000, ABILITY_POWER, HEALTH, ABILITY_HASTE, MOVEMENT),
    CRYPTBLOOM(3000, ABILITY_POWER, MAGIC_PENETRATION, ABILITY_HASTE), DAWNCORE(2500, ABILITY_POWER, MANA), DEAD_MANS_PLATE(2900, HEALTH, ARMOR, MOVEMENT), DEATHS_DANCE(3300, ATTACK_DAMAGE, ARMOR, ABILITY_HASTE), DUSK_AND_DAWN(3100, ATTACK_SPEED, ON_HIT, ABILITY_POWER, HEALTH, ABILITY_HASTE),
    ECHOES_OF_HELIA(2200, ABILITY_POWER, MANA, HEALTH), ECLIPSE(2900, ATTACK_DAMAGE, ABILITY_HASTE), EDGE_OF_NIGHT(3000, ATTACK_DAMAGE, ARMOR_PENETRATION, HEALTH), ENDLESS_HUNGER(3100, ATTACK_DAMAGE, ABILITY_HASTE, LIFE_STEAL),
    ESSENCE_REAVER(3050, ATTACK_DAMAGE, CRITICAL_CHANCE, ON_HIT, MANA, ABILITY_HASTE), EXPERIMENTAL_HEXPLATE(3000, ATTACK_DAMAGE, ATTACK_SPEED, HEALTH, ABILITY_HASTE, MOVEMENT), FIENDHUNTER_BOLTS(2650, CRITICAL_CHANCE, ATTACK_SPEED, ABILITY_HASTE, MOVEMENT),
    FORCE_OF_NATURE(2800, HEALTH, MAGIC_RESIST, MOVEMENT), FROZEN_HEART(2500, MANA, ARMOR, ABILITY_HASTE), GUARDIAN_ANGEL(3200, ATTACK_DAMAGE, ARMOR), GUINSOOS_RAGEBLADE(3000, ATTACK_DAMAGE, ATTACK_SPEED, ON_HIT, ABILITY_POWER), HEARTSTEEL(3000, HEALTH),
    HEXOPTICS_C44(2800, ATTACK_DAMAGE, CRITICAL_CHANCE), HEXTECH_GUNBLADE(3000, ATTACK_DAMAGE, ABILITY_POWER, LIFE_STEAL), HEXTECH_ROCKETBELT(2650, ABILITY_POWER, HEALTH, ABILITY_HASTE, MOVEMENT), HOLLOW_RADIANCE(2800, HEALTH, MAGIC_RESIST, ABILITY_HASTE),
    HORIZON_FOCUS(2700, ABILITY_POWER, ABILITY_HASTE), HUBRIS(2800, ATTACK_DAMAGE, ARMOR_PENETRATION, ABILITY_HASTE, ABILITY_HASTE), HULL_BREAKER(3000, ATTACK_DAMAGE, HEALTH, MOVEMENT), ICEBORN_GAUNTLET(2900, ON_HIT, HEALTH, ARMOR, ABILITY_HASTE),
    IMMORTAL_SHIELDBOW(3000, ATTACK_DAMAGE, CRITICAL_CHANCE), IMPERIAL_MANDATE(2250, ABILITY_POWER, MANA, ABILITY_HASTE), INFINITY_EDGE(3500, ATTACK_DAMAGE, CRITICAL_CHANCE), JAK_SHO_THE_PROTEAN(3200, HEALTH, ARMOR, MAGIC_RESIST), KAENIC_ROOKERN(2900, HEALTH, MAGIC_RESIST),
    KNIGHTS_VOW(2300, HEALTH, ARMOR, ABILITY_HASTE), KRAKEN_SLAYER(3000, ATTACK_DAMAGE, ATTACK_SPEED, ON_HIT, MOVEMENT), LIANDRYS_TORMENT(3000, ABILITY_POWER, HEALTH), LICH_BANE(2900, ON_HIT, ABILITY_POWER, ABILITY_HASTE, MOVEMENT),
    LOCKET_OF_THE_IRON_SOLARI(2200, HEALTH, ARMOR, MAGIC_RESIST, ABILITY_HASTE), LORD_DOMINIKS_REGARDS(3300, ATTACK_DAMAGE, CRITICAL_CHANCE, ARMOR_PENETRATION), LUDENS_ECHO(2750, ABILITY_POWER, MANA, ABILITY_HASTE), MALIGNANCE(2700, ABILITY_POWER, MANA, ABILITY_HASTE),
    MANAMUNE(2900, ATTACK_DAMAGE, ON_HIT, MANA, ABILITY_HASTE), MAW_OF_MALMORTIUS(3100, ATTACK_DAMAGE, MAGIC_RESIST, ABILITY_HASTE, LIFE_STEAL), MEJAIS_SOULSTEALER(1500, ABILITY_POWER, HEALTH, MOVEMENT), MERCURIAL_SCIMITAR(3200, ATTACK_DAMAGE, MAGIC_RESIST, MOVEMENT, LIFE_STEAL),
    MIKAELS_BLESSING(2300, MANA, HEALTH, ABILITY_HASTE), MOONSTONE_RENEWER(2200, ABILITY_POWER, MANA, HEALTH, ABILITY_HASTE), MORELLONOMICON(2850, ABILITY_POWER, HEALTH, ABILITY_HASTE), MORTAL_REMINDER(3000, ATTACK_DAMAGE, CRITICAL_CHANCE, ARMOR_PENETRATION),
    NASHORS_TOOTH(2900, ATTACK_SPEED, ON_HIT, ABILITY_POWER, ABILITY_HASTE), NAVORI_FLICKERBLADE(2650, CRITICAL_CHANCE, ATTACK_SPEED, MOVEMENT), OVERLORDS_BLOODMAIL(3300, ATTACK_DAMAGE, HEALTH),
    PHANTOM_DANCER(2650, CRITICAL_CHANCE, ATTACK_SPEED, MOVEMENT), PROFANE_HYDRA(2850, ATTACK_DAMAGE, ARMOR_PENETRATION, ABILITY_HASTE), PROTOPLASM_HARNESS(2500, HEALTH, ABILITY_HASTE, MOVEMENT), RABADONS_DEATHCAP(3500, ABILITY_POWER), RANDUINS_OMEN(2700, HEALTH, ARMOR),
    RAPID_FIRECANNON(2650, CRITICAL_CHANCE, ATTACK_SPEED, MOVEMENT), RAVENOUS_HYDRA(3300, ATTACK_DAMAGE, ON_HIT, ABILITY_HASTE, LIFE_STEAL), REDEMPTION(2300, ABILITY_POWER, MANA, ABILITY_HASTE), RIFTMAKER(3100, ABILITY_POWER, HEALTH, ABILITY_HASTE, LIFE_STEAL),
    ROD_OF_AGES(2600, ABILITY_POWER, MANA, HEALTH), RUNAANS_HURRICANE(2650, CRITICAL_CHANCE, ATTACK_SPEED, ON_HIT, MOVEMENT), RYLAIS_CRYSTAL_SCEPTER(2600, ABILITY_POWER, HEALTH), SERPENTS_FANG(2500, ATTACK_DAMAGE, ARMOR_PENETRATION),
    SERYLDAS_GRUDGE(3000, ATTACK_DAMAGE, ARMOR_PENETRATION, ABILITY_HASTE), SHADOWFLAME(3200, ABILITY_POWER, MAGIC_PENETRATION), SHURELYAS_BATTLESONG(2200, ABILITY_POWER, MANA, ABILITY_HASTE, MOVEMENT), SPEAR_OF_SHOJIN(3100, ATTACK_DAMAGE, HEALTH, ABILITY_HASTE),
    SPIRIT_VISAGE(2700, HEALTH, MAGIC_RESIST, ABILITY_HASTE), STAFF_OF_FLOWING_WATER(2200, ABILITY_POWER, MANA, ABILITY_HASTE), STATIKK_SHIV(3000, ATTACK_DAMAGE, ABILITY_POWER, ATTACK_SPEED, ON_HIT, MOVEMENT), STERAKS_GAGE(3200, ATTACK_DAMAGE, HEALTH),
    STORMRAZOR(3200, ATTACK_DAMAGE, CRITICAL_CHANCE, ATTACK_SPEED, MOVEMENT), STORMSURGE(2800, ABILITY_POWER, MAGIC_PENETRATION), STRIDE_BREAKER(3300, ATTACK_DAMAGE, ATTACK_SPEED, HEALTH), SUNDERED_SKY(3100, ATTACK_DAMAGE, HEALTH, ABILITY_HASTE), SUNFIRE_AEGIS(2700, HEALTH, ARMOR, ABILITY_HASTE),
    TERMINUS(3000, ATTACK_DAMAGE, ATTACK_SPEED, ON_HIT, ARMOR_PENETRATION, MAGIC_PENETRATION), THE_COLLECTOR(3000, ATTACK_DAMAGE, CRITICAL_CHANCE, ARMOR_PENETRATION), THORNMAIL(2450, HEALTH, ARMOR), TITANIC_HYDRA(3300, ATTACK_DAMAGE, ON_HIT, HEALTH),
    TRINITY_FORCE(3333, ATTACK_DAMAGE, ATTACK_SPEED, ON_HIT, HEALTH, ABILITY_HASTE, MOVEMENT), UMBRAL_GLAIVE(2800, ATTACK_DAMAGE, ARMOR_PENETRATION, ABILITY_HASTE), UNENDING_DESPAIR(2800, HEALTH, ARMOR, ABILITY_HASTE), VOID_STAFF(3000, ABILITY_POWER, MAGIC_PENETRATION),
    VOLTAIC_CYCLOSWORD(3000, ATTACK_DAMAGE, ARMOR_PENETRATION, ABILITY_HASTE), WARMOGS_ARMOR(3100, HEALTH), WHISPERING_CIRCLET(2250, MANA, HEALTH), WINTERS_APPROACH(2400, MANA, HEALTH, ABILITY_HASTE), WITS_END(2800, ATTACK_SPEED, ON_HIT, MAGIC_RESIST),
    YOUMUUS_GHOSTBLADE(2800, ATTACK_DAMAGE, ARMOR_PENETRATION, MOVEMENT), YUN_TAL_WILDARROWS(3100, ATTACK_DAMAGE, CRITICAL_CHANCE, ATTACK_SPEED), ZEKES_CONVERGENCE(2200, HEALTH, ARMOR, MAGIC_RESIST, ABILITY_HASTE), ZHONYAS_HOURGLASS(3250, ABILITY_POWER, ARMOR);

    private final @Getter int cost;
    private final @Getter Set<ItemProperty> properties;

    Item(final int cost, final ItemProperty... properties) {
        if (cost < 0) {
            throw new IllegalArgumentException();
        }
        this.cost = cost;
        this.properties = Collections.unmodifiableSet(new HashSet<>(List.of(properties)));
    }
}
