package de.glasergl.custom.lol.setup.model.entity;

public enum ItemProperty {
    ATTACK_DAMAGE, CRITICAL_CHANCE, ATTACK_SPEED, ON_HIT, ARMOR_PENETRATION, ABILITY_POWER, MANA, MAGIC_PENETRATION, HEALTH, ARMOR, MAGIC_RESIST, ABILITY_HASTE, MOVEMENT, LIFE_STEAL
}
