package de.glasergl.custom.lol.setup.model.entity;

public enum Rune {
    PRESS_THE_ATTACK, LETHAL_TEMPO, FLEET_FOOTWORK, CONQUEROR, ABSORB_LIFE, TRIUMPH, PRESENCE_OF_MIND, LEGEND_ALACRITY, LEGEND_HASTE, LEGEND_BLOODLINE, COUP_DE_GRACE, CUT_DOWN, LAST_STAND,

    ELECTROCUTE, DARK_HARVEST, HAIL_OF_BLADES, CHEAP_SHOT, TASTE_OF_BLOOD, SUDDEN_IMPACT, SIXTH_SENSE, GRISLY_MEMENTOS, DEEP_WARD, TREASURE_HUNTER, RELENTLESS_HUNTER, ULTIMATE_HUNTER,

    SUMMON_AERY, ARCANE_COMET, DEATHFIRE_TOUCH, STORMRAIDERS_SURGE, AXIOM_ARCANIST, MANAFLOW_BAND, NIMBUS_CLOAK, TRANSCENDENCE, CELERITY, ABSOLUTE_FOCUS, SCORCH, WATERWALKING, GATHERING_STORM,

    GRASP_OF_THE_UNDYING, AFTERSHOCK, GUARDIAN, DEMOLISH, FONT_OF_LIFE, SHIELD_BASH, CONDITIONING, SECOND_WIND, BONE_PLATING, OVERGROWTH, REVITALIZE, UNFLINCHING,

    GLACIAL_AUGMENT, UNSEALED_SPELLBOOK, FIRST_STRIKE, HEXTECH_FLASHTRAPTION, MAGICAL_FOOTWEAR, CASH_BACK, TRIPLE_TONIC, TIME_WARP_TONIC, BISCUIT_DELIVERY, COSMIC_INSIGHT, APPROACH_VELOCITY, JACK_OF_ALL_TRADES,

    OFFENSIVE_ADAPTIVE_FORCE, OFFENSIVE_ATTACK_SPEED, OFFENSIVE_ABILITY_HASTE, FLEX_ADAPTIVE_FORCE, FLEX_MOVEMENT_SPEED, FLEX_SCALING_HEALTH, DEFENSE_DIRECT_HEALTH, DEFENSE_TENACITY_SLOW_RESIST, DEFENSE_SCALING_HEALTH;
}
